import {equationBlock,modelSymbols,verifiedSources} from './equations.js';

export function renderModelPage({p,k,summary,material,fmt,head,footer,referencePanel}){
 const ratio=k.M*k.R*Math.sin(k.alpha)/(k.m*k.l);
 const equilibrium=k.c>0&&Math.abs(ratio)<1;
 const terminal=equilibrium?fmt(k.M*k.g*k.R*k.R*Math.sin(k.alpha)/k.c*1000,4)+' mm/s':'No interior steady-orbit branch for this setup';
 const note=(kind,text)=>`<p class="source-note"><span class="derivation-tag">${kind}</span>${text}</p>`;
 return head('The equations behind the motion.','Definitions, derivations and primary sources for the implemented model.')+`
 <div class="notice"><strong>Model scope:</strong> A homogeneous solid ball, a full Newtonian liquid cavity, rolling without slip and a prescribed film gap. The mechanics and fluid preview are approximations; the sources below do not establish experimental accuracy of this implementation.</div>
 <div class="content-grid model-page">
 <section class="card body-card full"><h2>01 / Symbols and sign conventions</h2><p>Internal calculations use SI units. Inputs in millimetres, grams and degrees are converted before integration. A dot denotes a time derivative.</p><p>Shell displacement increases downhill. Positive shell rotation is clockwise; positive core-centre angle is counterclockwise from the downward ramp normal. Consequently, co-rotation gives a core orbital rate opposite to the shell rate.</p>${equationBlock('rates')}${modelSymbols()}</section>
 <section class="card body-card"><h2>02 / Sphere geometry</h2>${equationBlock('geometry')}<p>The shell thickness is 1 mm. The core follows a circular orbit with a fixed minimum gap; settling and changing contact are omitted.</p><dl class="model-values"><div><dt>Minimum film</dt><dd>${fmt(p.gap,3)} mm</dd></div><div><dt>Orbit radius</dt><dd>${fmt(k.l*1000,3)} mm</dd></div></dl>${note('Direct derivation','Sphere volumes and the prescribed orbit follow from geometry. No fitted geometry factor is used.')}</section>
 <section class="card body-card"><h2>03 / Material and effective mass</h2>${equationBlock('mass')}<dl class="model-values"><div><dt>Inner material</dt><dd>${material?.name||'Custom solid'}</dd></div><div><dt>Core density</dt><dd>${fmt(p.core_density,1)} kg/m³</dd></div><div><dt>Calculated core mass</dt><dd>${fmt(k.mc*1000,2)} g</dd></div><div><dt>Liquid mass</dt><dd>${fmt(k.mf*1000,2)} g</dd></div></dl><p>Buoyant mass controls gravity. Relative inertial mass also accounts for the mean liquid-centre motion and is a different quantity. The liquid centre relative to the shell is opposite the core displacement, scaled by displaced-liquid mass divided by liquid mass.</p>${note('Sphere adaptation · [1]','Expanding core and mean-liquid translational kinetic energies gives the inertial mass above. Internal fluid circulation and free core spin are omitted. The core moment of inertia is used in the separate rigid reference.')}<p>${material?`<a href="${material.source}" target="_blank" rel="noopener">${material.name} nominal-density source ↗</a>`:'Use measured density for the custom solid.'}</p></section>
 <section class="card body-card full"><h2>04 / Coupled equations of motion</h2><p>The kinetic and potential energies define the Lagrangian. Euler–Lagrange equations with Rayleigh dissipation produce the following two coupled equations.</p>${equationBlock('coefficients')}${equationBlock('motion')}<p>The solver inverts this positive-definite 2 × 2 mass matrix at every RK4 stage. Initial shell displacement, shell speed and orbital speed are zero; the initial core angle is ${fmt(p.q0,2)}°.</p>${note('Derived for this app · [1, 2]','These are the equations actually integrated in physics.js and backend/model.py. The cylinder paper motivates the approach; its published equations are not being presented as a validated spherical solution.')}</section>
 <section class="card body-card"><h2>05 / Dissipation and energy balance</h2>${equationBlock('energy')}<p>Nonnegative viscous power converts mechanical energy to heat. Gravity can keep supplying energy even when acceleration tends to zero. Recoil, where present, comes from the coupled coordinates.</p><dl class="model-values"><div><dt>Maximum energy residual</dt><dd>${summary.residual.toExponential(2)} J</dd></div><div><dt>Integration step</dt><dd>${k.c===0?'Inviscid mechanics':'Damping-resolved RK4'}</dd></div></dl>${note('Energy identity','The displayed residual checks the numerical balance between mechanical energy and accumulated dissipation. It does not validate the hydrodynamic closure experimentally.')}</section>
 <section class="card body-card"><h2>06 / Approximate orbital resistance</h2>${equationBlock('gap')}<p>The cosine of the angle from the nearest-gap axis is denoted by μ. A local Newtonian shear estimate integrates tangential surface dissipation over the sphere. The angular projection gives the factor (1 + μ²)/2.</p><p>The integral uses 256 midpoint panels. No empirical confinement multiplier or extra bulk-drag term is added.</p>${note('Local shear approximation','This closure is derived for the app. It omits pressure-driven resistance, independent core spin and the rotational surface-shear contribution. It is not the exact eccentric-sphere resistance from a published solution.')}</section>
 <section class="card body-card full"><h2>07 / Navier–Stokes fluid preview</h2>${equationBlock('fluid')}${equationBlock('boundaries')}<p>The frame translates with the shell and does not rotate. Fluid velocity begins at zero. Both boundaries use no slip; the core translates with its calculated centre and has prescribed zero spin.</p><p>A staggered MAC grid uses semi-Lagrangian advection, implicit viscous diffusion and pressure projection. The mechanical trajectory drives the boundary motion; computed fluid stresses do not feed back into the mechanics.</p>${note('Numerical method · [3]','Stam supports the advection/diffusion/projection method. The moving raster boundaries and disconnected-region corrections here are implementation approximations. The 32–56 cell grid usually does not resolve the minimum film; this is a qualitative 2D preview, not converged 3D CFD.')}</section>
 <section class="card body-card full"><h2>08 / Analytical local gap profile</h2>${equationBlock('profile')}<p>Here y is distance across a locally parallel film and ξ is distance along it. U₀ and U₁ are the two specified boundary speeds. Integrating the steady creeping-flow equation with these boundary conditions gives the Couette–Poiseuille profile.</p><p>The Python flow endpoint evaluates this analytical expression. The live gap graph uses zero imposed pressure gradient and relative orbital translation speed. This local profile is separate from the whole-cavity pressure calculation.</p>${note('Analytical reduction','The formula follows by integrating the local steady Newtonian momentum balance twice. A parallel-gap approximation does not determine the global eccentric pressure field.')}</section>
 <section class="card body-card"><h2>09 / Why velocity can become constant</h2>${equationBlock('terminal')}<p>The stationary-orbit condition applies to positive downhill incline. The terminal speed requires positive resistance; a strict interior existence condition is needed for the displayed angle branch. Existence alone is not a stability proof.</p><dl class="model-values"><div><dt>Current steady speed</dt><dd>${terminal}</dd></div><div><dt>Equilibrium slope limit</dt><dd>${fmt(Math.asin(Math.min(1,k.m*k.l/(k.M*k.R)))*180/Math.PI,3)}°</dd></div></dl><p>The default trajectory approaches this balance after damped oscillations. Tiny finite-time acceleration is retained; it is not clamped to zero.</p>${note('Derived equilibrium','Set both accelerations and the core orbital rate to zero in the coupled equations. Velocity differences and half-step convergence checks verify the default numerical plateau.')}</section>
 <section class="card body-card"><h2>10 / Contact and validity checks</h2>${equationBlock('contact')}${equationBlock('reynolds')}<p>Contact requires positive normal force and a measured static friction coefficient at least as large as the required ratio. Slip and lift-off are not integrated. The Reynolds estimate requires nonzero viscosity; low Reynolds number alone does not validate the gap closure.</p><dl class="model-values"><div><dt>Sampled required friction</dt><dd>${fmt(summary.required_friction,4)}</dd></div><div><dt>Minimum normal force</dt><dd>${fmt(summary.min_normal,3)} N</dd></div></dl>${note('Momentum balance','The contact forces follow from the total centre-of-mass acceleration, including the displaced core and mean fluid. Compare them with your measured ramp properties.')}</section>
 <section class="card body-card full"><h2>11 / Experimental constants</h2><p>Measure actual radius, density, liquid viscosity at temperature, minimum gap, fill level and incline. Compare repeated shell and core trajectories with uncertainties. A constant-speed fit alone cannot validate all assumptions.</p><div class="control-line"><label>Shell mass <input id="advanced-shell" type="number" min="1" max="2000" step="any" value="${p.shell}"> g</label><label>Fluid density <input id="advanced-rho" type="number" min="100" max="3000" step="any" value="${p.rho}"> kg/m³</label><label>Film gap <input id="advanced-gap" type="number" min=".05" max="10" step="any" value="${p.gap}"> mm</label><label>Initial q <input id="advanced-q0" type="number" min="-60" max="60" value="${p.q0}"> °</label><button id="apply-advanced" class="primary">Apply constants</button></div><p><a href="./PHYSICS.md" target="_blank" rel="noopener">Full derivation and verification notes ↗</a></p></section>
 ${verifiedSources()}${referencePanel()}</div>`+footer();
}
